fix(fastly): guard against missing gateway name
when no `--fastly-gateway` parameter has been set, then deploying to Fastly Compute fails

```
--: uploading package to fastly, service version 5
--: creating secrets dictionary
--: updating gateway backend:
error: Fastly Compute@Edge - Address 'address' is not a valid IPv4, IPv6 or hostname
error: aborted due to errors during deploy
```

this is caused by a server-side validation on the fastly end. The fix will make sure host
is set before trying to update the gateway host.